main_wishlist:
    resource: "@MainBundle/Controller/wishlistController.php"
    type:     annotation

main_event:
    resource: "@MainBundle/Controller/EventController.php"
    type:     annotation

main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"
main_article:
        resource: "@MainBundle/Resources/config/routing/article.yml"
        prefix:   /article
