breed_index:
    path:     /
    defaults: { _controller: "MainBundle:Breed:index" }
    methods:  GET

breed_show:
    path:     /{id}/show
    defaults: { _controller: "MainBundle:Breed:show" }
    methods:  GET

breed_new:
    path:     /new
    defaults: { _controller: "MainBundle:Breed:new" }
    methods:  [GET, POST]

breed_edit:
    path:     /{id}/edit
    defaults: { _controller: "MainBundle:Breed:edit" }
    methods:  [GET, POST]

breed_delete:
    path:     /{id}/delete
    defaults: { _controller: "MainBundle:Breed:delete" }
    methods:  DELETE
