main_animal:
        resource: "@MainBundle/Resources/config/routing/animal.yml"
        prefix:   /animal
main_adoption:
        resource: "@MainBundle/Resources/config/routing/adoption.yml"
        prefix:   /adoption

main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Default:index }
services_multi:
    path:     /services
    defaults: { _controller: MainBundle:Default:services}
pets_multi:
    path:     /pets
    defaults: { _controller: MainBundle:Default:pets}
contact:
    path:     /contact
    defaults: { _controller: MainBundle:Default:contact}
leisure:
    path:     /leisure
    defaults: { _controller: MainBundle:Default:leisure}
products:
    path:     /products
    defaults: { _controller: MainBundle:Default:products}
singlepet:
    path:     /singlepet
    defaults: { _controller: MainBundle:Default:singlepet}
admin-index:
     path:     /admin/index
     defaults: { _controller: MainBundle:Admin:index}

admin-user-table:
     path:     /admin/usertable
     defaults: { _controller: MainBundle:Admin:usertable}
admin-events-table:
     path:     /admin/events
     defaults: { _controller: MainBundle:Admin:eventstable}
admin-articles-table:
     path:     /admin/articles
     defaults: { _controller: MainBundle:Admin:articlestable}
admin-pets-table:
     path:     /admin/pets
     defaults: { _controller: MainBundle:Admin:petstable}
admin-delete-event:
    path:     /admin/eventdelete/{id}
    defaults: { _controller: MainBundle:Admin:eventsdelete }
admin-validate-event:
    path:     /admin/eventvalidate/{id}
    defaults: { _controller: MainBundle:Admin:validate }

calendar:
     path:     /calendar
     defaults: { _controller: MainBundle:Default:calendar}
myevents:
     path:     /myevents
     defaults: { _controller: MainBundle:Event:myevents}
addreservation:
     path:     /reservation/{uid}/{eid}/
     defaults: { _controller: MainBundle:Reservation:reservation}
deletereservation:
     path:     /reservation/delete/{uid}/{eid}/
     defaults: { _controller: MainBundle:Reservation:delete}
nextevent:
     path:     /event/{id}/nextevent
     defaults: { _controller: MainBundle:Event:nextevent}
previousevent:
     path:     /event/{id}/previous
     defaults: { _controller: MainBundle:Event:previousevent}
gallery:
     path:     /gallery
     defaults: { _controller: MainBundle:Event:gallery}
pdfinvitation:
     path:     /invitation/{eid}/{uid}
     defaults: { _controller: MainBundle:Event:pdfinvitation}
main_pet:
        resource: "@MainBundle/Resources/config/routing/pet.yml"
        prefix:   /pet
main_product:
        resource: "@MainBundle/Resources/config/routing/product.yml"
        prefix:   /product
main_image:
        resource: "@MainBundle/Resources/config/routing/image.yml"
        prefix:   /image
addtowishlist:
     path:     /addtowishlist/{id}
     defaults: { _controller: MainBundle:wishlist:addtowishlist}
deletefromwishlist:
     path:     /deletefromwishlist/{id}
     defaults: { _controller: MainBundle:wishlist:deletefromwishlist}
mgilet_notifications:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications
main_office:
    resource: "@MainBundle/Resources/config/routing/office.yml"
    prefix:   /office
main_appointment:
        resource: "@MainBundle/Resources/config/routing/appointment.yml"
        prefix:   /appointment
mesrendezvous:
     path:     /mesrendezvous
     defaults: { _controller: MainBundle:Appointment:mesrendezvous}
afficheoffice:
     path:     /afficheoffice
     defaults: { _controller: MainBundle:Appointment:afficheoffice}
ajoutrdv:
     path:     /ajoutrdv
     defaults: { _controller: MainBundle:Appointment:ajoutrdv}
SupprimerRdv:
     path:     /SupprimerRdv
     defaults: { _controller: MainBundle:Appointment:SupprimerRdv}
myofficeappointment:
     path:     /myofficeappointment
     defaults: { _controller: MainBundle:Appointment:myofficeappointment}
pdfrdv:
     path:     /pdfrdv/{id}
     defaults: { _controller: MainBundle:Appointment:pdfrdv}
mywishlist:
     path:     /mywishlist
     defaults: { _controller: MainBundle:wishlist:mywishlist}
mycomplaints:
     path:     /mycomplaints
     defaults: { _controller: MainBundle:Complaint:mycomplaints}
event_recherche_ajax:
     path:     /event_recherche_ajax
     defaults: { _controller: MainBundle:Event:chercher}


