main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Default:index }
services_multi:
    path:     /services
    defaults: { _controller: MainBundle:Default:services}
pets_multi:
    path:     /pets
    defaults: { _controller: MainBundle:Default:pets}
contact:
    path:     /contact
    defaults: { _controller: MainBundle:Default:contact}
leisure:
    path:     /leisure
    defaults: { _controller: MainBundle:Default:leisure}
products:
    path:     /products
    defaults: { _controller: MainBundle:Default:products}
singlepet:
    path:     /singlepet
    defaults: { _controller: MainBundle:Default:singlepet}

