main_animal:
        resource: "@MainBundle/Resources/config/routing/animal.yml"
        prefix:   /animal
main_adoption:
        resource: "@MainBundle/Resources/config/routing/adoption.yml"
        prefix:   /adoption

main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Default:index }
services_multi:
    path:     /services
    defaults: { _controller: MainBundle:Default:services}
pets_multi:
    path:     /pets
    defaults: { _controller: MainBundle:Default:pets}
contact:
    path:     /contact
    defaults: { _controller: MainBundle:Default:contact}
leisure:
    path:     /leisure
    defaults: { _controller: MainBundle:Default:leisure}
products:
    path:     /products
    defaults: { _controller: MainBundle:Default:products}
singlepet:
    path:     /singlepet
    defaults: { _controller: MainBundle:Default:singlepet}
admin-index:
     path:     /admin/index
     defaults: { _controller: MainBundle:Admin:index}

admin-user-table:
     path:     /admin/usertable
     defaults: { _controller: MainBundle:Admin:usertable}
admin-events-table:
     path:     /admin/events
     defaults: { _controller: MainBundle:Admin:eventstable}
admin-articles-table:
     path:     /admin/articles
     defaults: { _controller: MainBundle:Admin:articlestable}
admin-delete-event:
    path:     /admin/eventdelete/{id}
    defaults: { _controller: MainBundle:Admin:eventsdelete }
admin-validate-event:
    path:     /admin/eventvalidate/{id}
    defaults: { _controller: MainBundle:Admin:validate }

calendar:
     path:     /calendar
     defaults: { _controller: MainBundle:Default:calendar}
myevents:
     path:     /myevents
     defaults: { _controller: MainBundle:Event:myevents}
addreservation:
     path:     /reservation/{uid}/{eid}/
     defaults: { _controller: MainBundle:Reservation:reservation}
deletereservation:
     path:     /reservation/delete/{uid}/{eid}/
     defaults: { _controller: MainBundle:Reservation:delete}
nextevent:
     path:     /event/{id}/nextevent
     defaults: { _controller: MainBundle:Event:nextevent}
previousevent:
     path:     /event/{id}/previous
     defaults: { _controller: MainBundle:Event:previousevent}
pdfinvitation:
     path:     /invitation/{eid}/{uid}
     defaults: { _controller: MainBundle:Event:pdfinvitation}

add_product:
     path:     products/add
     defaults: { _controller: MainBundle:Product:addProduct}
index_product:
     path:     products/index
     defaults: { _controller: MainBundle:Product:indexProduct}
delete_product:
     path:     products/{id}/delete
     defaults: { _controller: MainBundle:Product:deleteProduct}
edit_product:
     path:     products/{id}/edit
     defaults: { _controller: MainBundle:Product:editProduct}

add_product_category:
     path:     products/addcategory
     defaults: { _controller: MainBundle:ProductCategory:addProductCategory}