main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Default:index }
services_multi:
    path:     /services
    defaults: { _controller: MainBundle:Default:services}
pets_multi:
    path:     /pets
    defaults: { _controller: MainBundle:Default:pets}
contact:
    path:     /contact
    defaults: { _controller: MainBundle:Default:contact}
leisure:
    path:     /leisure
    defaults: { _controller: MainBundle:Default:leisure}
products:
    path:     /products
    defaults: { _controller: MainBundle:Default:products}
singlepet:
    path:     /singlepet
    defaults: { _controller: MainBundle:Default:singlepet}
admin-index:
     path:     /admin/index
     defaults: { _controller: MainBundle:Admin:index}

admin-user-table:
     path:     /admin/usertable
     defaults: { _controller: MainBundle:Admin:usertable}
admin-events-table:
     path:     /admin/events
     defaults: { _controller: MainBundle:Admin:eventstable}
admin-delete-event:
    path:     /admin/eventdelete/{id}
    defaults: { _controller: MainBundle:Admin:eventsdelete }
admin-validate-event:
    path:     /admin/eventvalidate/{id}
    defaults: { _controller: MainBundle:Admin:validate }

calendar:
     path:     /calendar
     defaults: { _controller: MainBundle:Default:calendar}
myevents:
     path:     /myevents
     defaults: { _controller: MainBundle:Event:myevents}
addreservation:
     path:     /reservation/{uid}/{eid}/
     defaults: { _controller: MainBundle:Reservation:reservation}


